spring.application.name=springboot-blog-rest-api

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/rest_blog
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Specify the MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Specify the JWT secret
jwt.secret=47dccc6651735af3fac3d84af843de6326ae188ef26284956218e63d1ffa4435
jwt.expiration=604800000
